### PR TITLE
implemented create and delete backend into frontend interface, deleting returns error but still deletes contents

### PR DESCRIPTION
**Pull request by JeffyWongo**

### CODE REVIEW

**Comment by paul-ngyn** [comment]
LGTM

**Review by paul-ngyn — COMMENTED** [review]
LGTM

**Review by HWFord16 — APPROVED** [review]
only suggestion i have is the create directory function. Maybe we can split it to where we separately create the parent Directory and the sub directories. Because right now that function creates 3 sub directories immediately if  the parent directories exists.

**Comment by HWFord16** [comment]
approving merge to get latest files in main before the restructuring of main. More additional changes will most likely be needed but we can create a new branch to do so.

**Pull request merged**
